---
template:
  id: puppet-content-template
  author: puppetlabs
  type: project
  display: Puppet Content Template
  version: 0.1.0
  url: https://github.com/puppetlabs/pct

puppet_content_template:
  author: <Replace with author id, e.g. 'puppetlabs'>