---
template:
  id: rsapi-provider
  author: puppetlabs
  display: Puppet Resource API Provider
  type: item
  version: 0.1.0
  url: https://github.com/puppetlabs/pct-rsapi-provider

rsapi:
  attributes:
    - name: foo
      type: String
      desc: The foo of the resource you want to manage