---
template:
  id: bolt-plan
  author: puppetlabs
  type: item
  display: "Bolt Plan"
  version: 0.1.0
  url: https://github.com/puppetlabs/pct-bolt-plan

bolt_plan:
  module: <CHANGE_TO_MODULE_NAME>