---
template:
  id: bolt-pwsh-task
  author: puppetlabs
  type: item
  display: "Bolt PowerShell Task"
  version: 0.1.0
  url: https://github.com/puppetlabs/pct-bolt-pwsh-task

bolt_pwsh_task:
  description: A Geneterated Powershell Bolt Task
  parameters:
    - name: name
      type: String
    - name: param_two
      type: String